// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3inWhdi0ZK7WL7OVcsFhOFOBLbH1nTVs',
    appId: '1:590544700984:android:21a75f6b7c6a1fd16988cd',
    messagingSenderId: '590544700984',
    projectId: 'webfirebase-c0348',
    storageBucket: 'webfirebase-c0348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAlJuyACkRtpSZtDZ6ysZ6LiZRqbv5f5M',
    appId: '1:590544700984:ios:d942c35ffdc8c8456988cd',
    messagingSenderId: '590544700984',
    projectId: 'webfirebase-c0348',
    storageBucket: 'webfirebase-c0348.appspot.com',
    androidClientId: '590544700984-vk2oqae8cr3otj5idrtukq0epvl59v00.apps.googleusercontent.com',
    iosClientId: '590544700984-1qol85qjo6ug0qulecnfercb831pocl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListV2',
  );
}
